# Generated by Django 3.0.6 on 2020-05-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SqlServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('cod1c7', models.CharField(db_index=True, max_length=3)),
                ('sql_base', models.CharField(max_length=100)),
                ('tr5_path', models.CharField(max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.Region')),
                ('sql_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.SqlServer')),
            ],
        ),
    ]
